sudo: false
language: node_js
node_js: stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
cache:
  directories:
  - node_modules
  - bower_modules
before_install:
- export CC=/usr/bin/gcc-4.9
- export CXX=/usr/bin/g++-4.9
install:
- npm install
- ./node_modules/.bin/typings install
- ./node_modules/.bin/bower install
before_script:
- git config --global user.name "Lorem Ipsum"
- git config --global user.email lorem-ipsum@example.com
- npm run build
script:
- npm test
